#include "ui/theme.hpp"

#include <fstream>
#include <sstream>

#include "ui/ui_helpers.h"

#include <dwarfkit/core/json.hpp>

#include "core/paths.hpp"

// Embedded font data (generated by tb_embed at build time).
#include "font_rajdhani_bold.h"
#include "font_rajdhani_medium.h"
#include "font_rajdhani_regular.h"
#include "font_rajdhani_semibold.h"
#include "font_sharetech_mono.h"

namespace tb::ui {

Fonts& fonts() {
    static Fonts f;
    return f;
}

namespace {
float g_dpiScale = 1.0f;
}

float dpiScale() { return g_dpiScale; }

Cosmetics& cosmetics() {
    static Cosmetics c;
    return c;
}

void loadCosmetics() {
    std::ifstream in(settingsFile());
    if (!in) return;
    std::stringstream buffer;
    buffer << in.rdbuf();
    auto j = dwarfkit::json::parse(buffer.str(), nullptr, false);
    if (j.is_discarded() || !j.is_object()) return;
    cosmetics().glow = j.value("glow", 1.0f);
    cosmetics().reduceMotion = j.value("reduceMotion", false);
    cosmetics().preferHighPerfGpu = j.value("preferHighPerfGpu", true);
    if (cosmetics().glow < 0.0f) cosmetics().glow = 0.0f;
    if (cosmetics().glow > 1.0f) cosmetics().glow = 1.0f;
}

void saveCosmetics() {
    dwarfkit::json j{{"glow", cosmetics().glow},
                     {"reduceMotion", cosmetics().reduceMotion},
                     {"preferHighPerfGpu", cosmetics().preferHighPerfGpu}};
    atomicWrite(settingsFile(), j.dump(2), /*keepBackup=*/false);
}

static ImFont* addFont(const unsigned char* data, unsigned size) {
    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;  // arrays live in the binary
    return ImGui::GetIO().Fonts->AddFontFromMemoryTTF(
        const_cast<unsigned char*>(data), static_cast<int>(size), 0.0f, &cfg);
}

void initTheme(float contentScale) {
    g_dpiScale = contentScale > 0.0f ? contentScale : 1.0f;
    ::ui::gScale = g_dpiScale;  // ui_helpers.h S() shares the same boot scale
    ImGuiIO& io = ImGui::GetIO();
    Fonts& f = fonts();
    f.ui = addFont(font_rajdhani_regular, font_rajdhani_regular_size);
    f.uiMedium = addFont(font_rajdhani_medium, font_rajdhani_medium_size);
    f.uiSemi = addFont(font_rajdhani_semibold, font_rajdhani_semibold_size);
    f.uiBold = addFont(font_rajdhani_bold, font_rajdhani_bold_size);
    f.mono = addFont(font_sharetech_mono, font_sharetech_mono_size);
    io.FontDefault = f.uiMedium;

    ImGuiStyle& s = ImGui::GetStyle();
    s = ImGuiStyle();  // reset before rescale

    // Geometry: angular, thin, precise.
    s.WindowPadding = {0, 0};
    s.WindowBorderSize = 0;
    s.WindowRounding = 0;
    s.FramePadding = {12, 8};
    s.FrameRounding = 3;
    s.FrameBorderSize = 1;
    s.ItemSpacing = {10, 10};
    s.ItemInnerSpacing = {8, 6};
    s.CellPadding = {10, 7};
    s.ScrollbarSize = 10;
    s.ScrollbarRounding = 5;
    s.GrabRounding = 3;
    s.GrabMinSize = 12;
    s.PopupRounding = 4;
    s.PopupBorderSize = 1;
    s.ChildRounding = 5;
    s.ChildBorderSize = 1;
    s.TabRounding = 3;
    s.SelectableTextAlign = {0, 0.5f};
    s.WindowTitleAlign = {0.5f, 0.5f};
    s.DisabledAlpha = 0.45f;
    s.HoverStationaryDelay = 0.35f;

    ImVec4* c = s.Colors;
    using namespace col;
    c[ImGuiCol_WindowBg] = vec(Bg);
    c[ImGuiCol_ChildBg] = {0, 0, 0, 0};
    c[ImGuiCol_PopupBg] = vec(rgba(0x0B1422, 0xF8));
    c[ImGuiCol_Border] = vec(Hairline);
    c[ImGuiCol_BorderShadow] = {0, 0, 0, 0};
    c[ImGuiCol_FrameBg] = vec(Inset);
    c[ImGuiCol_FrameBgHovered] = vec(rgba(0x0A1526));
    c[ImGuiCol_FrameBgActive] = vec(rgba(0x0C1B30));
    c[ImGuiCol_TitleBg] = vec(Bg);
    c[ImGuiCol_TitleBgActive] = vec(Bg);
    c[ImGuiCol_Text] = vec(Ice);
    c[ImGuiCol_TextDisabled] = vec(Slate);
    c[ImGuiCol_CheckMark] = vec(Cyan);
    c[ImGuiCol_SliderGrab] = vec(CyanDim);
    c[ImGuiCol_SliderGrabActive] = vec(Cyan);
    c[ImGuiCol_Button] = vec(rgba(0x0E1E31));
    c[ImGuiCol_ButtonHovered] = vec(rgba(0x143049));
    c[ImGuiCol_ButtonActive] = vec(rgba(0x1B4262));
    c[ImGuiCol_Header] = vec(rgba(0x0E1E31));
    c[ImGuiCol_HeaderHovered] = vec(rgba(0x143049));
    c[ImGuiCol_HeaderActive] = vec(rgba(0x1B4262));
    c[ImGuiCol_Separator] = vec(Hairline);
    c[ImGuiCol_SeparatorHovered] = vec(HairHi);
    c[ImGuiCol_SeparatorActive] = vec(Cyan);
    c[ImGuiCol_ResizeGrip] = {0, 0, 0, 0};
    c[ImGuiCol_ScrollbarBg] = {0, 0, 0, 0};
    c[ImGuiCol_ScrollbarGrab] = vec(rgba(0x16293D));
    c[ImGuiCol_ScrollbarGrabHovered] = vec(rgba(0x1E3A57));
    c[ImGuiCol_ScrollbarGrabActive] = vec(rgba(0x2A4E73));
    c[ImGuiCol_Tab] = vec(Panel);
    c[ImGuiCol_TabHovered] = vec(rgba(0x143049));
    c[ImGuiCol_TabSelected] = vec(rgba(0x11253C));
    c[ImGuiCol_TableHeaderBg] = vec(rgba(0x0B1523));
    c[ImGuiCol_TableBorderStrong] = vec(Hairline);
    c[ImGuiCol_TableBorderLight] = vec(rgba(0x0F1E2F));
    c[ImGuiCol_TableRowBg] = {0, 0, 0, 0};
    c[ImGuiCol_TableRowBgAlt] = vec(rgba(0x0A1420, 0x66));
    c[ImGuiCol_TextSelectedBg] = vec(rgba(0x00E0FF, 0x33));
    c[ImGuiCol_ModalWindowDimBg] = {0.008f, 0.016f, 0.035f, 0.78f};
    c[ImGuiCol_NavCursor] = vec(CyanFaint);

    s.ScaleAllSizes(contentScale);
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    io.IniFilename = nullptr;  // fixed layout; nothing to remember
}

}  // namespace tb::ui
