/* tb_embed: convert any file into a C header with a byte array.
 *
 *   tb_embed <input> <output.h> <symbol>
 *
 * Emits `const unsigned char <symbol>[]` and `const unsigned int <symbol>_size`.
 * Used at build time to bake fonts into the TackleBox binary so the shipped
 * app is a single self-contained executable. */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: tb_embed <input> <output.h> <symbol>\n");
        return 1;
    }
    FILE* in = fopen(argv[1], "rb");
    if (!in) {
        fprintf(stderr, "tb_embed: cannot open %s\n", argv[1]);
        return 1;
    }
    FILE* out = fopen(argv[2], "wb");
    if (!out) {
        fprintf(stderr, "tb_embed: cannot create %s\n", argv[2]);
        fclose(in);
        return 1;
    }
    fprintf(out, "/* Generated by tb_embed from %s. Do not edit. */\n", argv[1]);
    fprintf(out, "static const unsigned char %s[] = {\n", argv[3]);
    unsigned long total = 0;
    unsigned char buf[4096];
    size_t n;
    while ((n = fread(buf, 1, sizeof buf, in)) > 0) {
        for (size_t i = 0; i < n; ++i) {
            fprintf(out, "%u,", (unsigned)buf[i]);
            if (++total % 32 == 0) fputc('\n', out);
        }
    }
    fprintf(out, "\n};\nstatic const unsigned int %s_size = %lu;\n", argv[3], total);
    fclose(in);
    fclose(out);
    return 0;
}
